name: Auto Tag

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.VELOPACK_GITHUB_TOKEN }}

      - name: Determine and create next version tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.VELOPACK_GITHUB_TOKEN }}
          default_bump: patch
          tag_prefix: v
          release_branches: main
          pre_release_branches: ""
          append_to_pre_release_tag: ""
          dry_run: false
