name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Build icon resource
        run: windres -o icon.syso icon.rc

      - name: Build binary
        run: |
          $version = "${{ github.ref_name }}"
          if ($version.StartsWith("v")) { $version = $version.Substring(1) }
          go build -ldflags "-H=windowsgui -X main.currentVersion=$version" -o GloriousBatteryMonitor-Go.exe

      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/changelog-config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: GloriousBatteryMonitor-Go.exe
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          generate_release_notes: false
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}